### ISSUE TITLE
Support for single VCF file

### ISSUE THREAD

**Issue by LatinSuD** [nbeaver/vcard2csv#4]
I got a dump where I got a single big VCF file that has all the contacts one after the other.

I splitted them using this awk script, but it would be nice if the code was able to process multi-contact VCF files.

```
cat input.vcf | awk '
   {S=S $0 "\n"}
   /^END:VCARD/ { print S > NR".vcf"; S="" }
   END          { print S > NR".vcf"; S="" }
'
```

**Comment by nbeaver** [comment]
This should be fixed by https://github.com/nbeaver/vcard2csv/commit/9ec0a0ce0433f442bb36b8b6ed505ed6a0aa6587
